### ISSUE TITLE
adding the other ebpf metrics 

### ISSUE THREAD

**Issue by JulianLegler** [maseiler/swms-monitoring#42]
Once we had the following ebpf programms implemented, but for demonstration cases we have currently just one:

- [x] cachestat
- [x] bio
- [x] dcstat
- [x] runqlat
- [x] syslat

they can be found here: https://github.com/cloudflare/ebpf_exporter/tree/master/examples

We have to extend them by adding our lable definitions to the labels section:

```yaml
                - name: dag_id
                  size: 8
                  decoders:
                    - name: airflow_dag_id
                - name: run_id
                  size: 8
                  decoders:
                    - name: airflow_run_id
                - name: task_id
                  size: 8
                  decoders:
                    - name: airflow_task_id
```

and extend the code section. Here we have to add 3 new variables to the existing struct (e.g. struct key_t for cachestat) and in the actual functions do something like this:
```c
u64 id = bpf_get_current_pid_tgid();
u64 pid = id >> 32; // PID is higher part
struct key_t key = { .ip = PT_REGS_IP(ctx) - 1, .pid = pid, .pid2 = pid, .pid3 = pid };
``` 

Definition of done:
show us in Prometheus that all metrics are available and that they all export the dag_id, run_id and task_id
